In [1]:
import pandas as pd

### Reading Excel Files

In [5]:
pd.read_excel('Data Sets/college.xlsx')

    Roll No            Name    City Department
0         1  Dal Chand Yogi  Jaipur        CSE
1         2        Mithlesh   alwar        ECE
2         3          Seema     kota       MECH
3         4           Saroj  jaipur        CSE
4         5          Suresh    kota        CSE
5         6           Ashok   alwar        CSE
6         7        Rohitash  Jaipur       MECH
7         8          Kelash  Jaipur     CIVIAL
8         9          Roshan  Jaipur       MECH
9        10          Lakhan    kota        ECE
10       11           Tulsi    kota        ECE
11       12          Payal    alwar        ECE
12       13         Manisha   alwar        CSE
13       14          Prinka   alwar        CSE
14       15         Shivani   alwar        ECE

In [6]:
pd.read_excel('Data Sets/college.xlsx', sheet_name='teachers')

   TeacherID      Name  Salary
0          1   Sameera   40000
1          2    Naveen   20000
2          3    Deepak   10000
3          4    Rajesh  100000
4          5     Sweta   40000
5          6  Sikander   90000
6          7  Aasutosh   50000
7          8     Aanju   30000

In [7]:
pd.read_excel('Data Sets/college.xlsx', sheet_name='students')

    Roll No            Name    City Department
0         1  Dal Chand Yogi  Jaipur        CSE
1         2        Mithlesh   alwar        ECE
2         3          Seema     kota       MECH
3         4           Saroj  jaipur        CSE
4         5          Suresh    kota        CSE
5         6           Ashok   alwar        CSE
6         7        Rohitash  Jaipur       MECH
7         8          Kelash  Jaipur     CIVIAL
8         9          Roshan  Jaipur       MECH
9        10          Lakhan    kota        ECE
10       11           Tulsi    kota        ECE
11       12          Payal    alwar        ECE
12       13         Manisha   alwar        CSE
13       14          Prinka   alwar        CSE
14       15         Shivani   alwar        ECE

### Reading Text Files

In [11]:
pd.read_csv('Data Sets/question_ans.txt')

ParserError: Error tokenizing data. C error: Expected 1 fields in line 12, saw 2

In [12]:
pd.read_csv('Data Sets/question_ans.txt', sep='\t')

,ArticleTitle,Question,Answer,DifficultyFromQuestioner,DifficultyFromAnswerer,ArticleFile
0,Abraham_Lincoln,Was Abraham Lincoln the sixteenth President of...,yes,easy,easy,S08_set3_a4
1,Abraham_Lincoln,Was Abraham Lincoln the sixteenth President of...,Yes.,easy,easy,S08_set3_a4
2,Abraham_Lincoln,Did Lincoln sign the National Banking Act of 1...,yes,easy,medium,S08_set3_a4
3,Abraham_Lincoln,Did Lincoln sign the National Banking Act of 1...,Yes.,easy,easy,S08_set3_a4
4,Abraham_Lincoln,Did his mother die of pneumonia?,no,easy,medium,S08_set3_a4
5,Abraham_Lincoln,Did his mother die of pneumonia?,No.,easy,easy,S08_set3_a4
6,Abraham_Lincoln,How many long was Lincoln's formal education?,18 months,medium,easy,S08_set3_a4
7,Abraham_Lincoln,How many long was Lincoln's formal education?,18 months.,medium,medium,S08_set3_a4
8,Abraham_Lincoln,When did Lincoln begin his political career?,1832,medium,easy,S08_set3_a4
9,Abraham_Lincoln,When did Lincoln begin his political career?,1832.,medium,medium,S08_set3_a4
10,Abraham_Lincoln,What did The Legal Tender Act of 1862 establish?,"the United States Note, the first paper curren...",medium,easy,S08_set3_a4
11,Abraham_Lincoln,What did The Legal Tender Act of 1862 establish?,"The United States Note, the first paper curren...",medium,medium,S08_set3_a4
12,Abraham_Lincoln,Who suggested Lincoln grow a beard?,11-year-old Grace Bedell,hard,medium,S08_set3_a4
13,Abraham_Lincoln,Who suggested Lincoln grow a beard?,Grace Bedell.,hard,medium,S08_set3_a4
14,Abraham_Lincoln,When did the Gettysburg address argue that Ame...,1776,hard,hard,S08_set3_a4
15,Abraham_Lincoln,When did the Gettysburg address argue that Ame...,1776.,hard,hard,S08_set3_a4
16,Abraham_Lincoln,Did Lincoln beat John C. Breckinridge in the 1...,yes,hard,medium,S08_set3_a4
17,Abraham_Lincoln,Did Lincoln beat John C. Breckinridge in the 1...,Yes.,hard,hard,S08_set3_a4
18,Abraham_Lincoln,Was Abraham Lincoln the first President of the...,No,easy,easy,S08_set3_a4
19,Abraham_Lincoln,Was Abraham Lincoln the first President of the...,No,easy,medium,S08_set3_a4
20,Abraham_Lincoln,Did Lincoln start his political career in 1832?,Yes,easy,easy,S08_set3_a4
21,Abraham_Lincoln,Did Lincoln start his political career in 1832?,Yes,easy,easy,S08_set3_a4
22,Abraham_Lincoln,Did Lincoln ever represent Alton & Sangamon Ra...,Yes,easy,easy,S08_set3_a4
23,Abraham_Lincoln,Did Lincoln ever represent Alton & Sangamon Ra...,Yes,easy,easy,S08_set3_a4
24,Abraham_Lincoln,Which county was Lincoln born in?,Hardin County,medium,medium,S08_set3_a4
25,Abraham_Lincoln,Which county was Lincoln born in?,"Southeast Hardin County, Kentucky",medium,medium,S08_set3_a4
26,Abraham_Lincoln,When did Lincoln first serve as President?,"March 4, 1861",medium,hard,S08_set3_a4
27,Abraham_Lincoln,When did Lincoln deliver the Gettysburg Address?,"November 19, 1863",medium,easy,S08_set3_a4
28,Abraham_Lincoln,When did Lincoln deliver the Gettysburg Address?,"November 19, 1863.",medium,medium,S08_set3_a4
29,Abraham_Lincoln,Which speech included 'Four score and seven ye...,Gettysburg Address,easy,easy,S08_set3_a4
30,Abraham_Lincoln,Which speech included 'Four score and seven ye...,The Gettysburg Address.,easy,medium,S08_set3_a4
31,Abraham_Lincoln,Who assassinated Abraham Lincoln?,John Wilkes Booth,easy,easy,S08_set3_a4
32,Abraham_Lincoln,Who assassinated Abraham Lincoln?,John Wilkes Booth.,easy,easy,S08_set3_a4
33,Abraham_Lincoln,Where was Lincoln assassinated?,Ford's Theatre,easy,medium,S08_set3_a4
34,Abraham_Lincoln,Where was Lincoln assassinated?,"Ford's Theatre in Washington, D.C.",easy,easy,S08_set3_a4
35,Abraham_Lincoln,When was the Emancipation Proclamation issued?,"January 1, 1863",medium,medium,S08_set3_a4
36,Abraham_Lincoln,When was the Emancipation Proclamation issued?,"January 1, 1863.",medium,easy,S08_set3_a4
37,Abraham_Lincoln,Who was Lincoln's Vice President during his se...,Andrew Johnson,hard,medium,S08_set3_a4
38,Abraham_Lincoln,Who was Lincoln's Vice President during his se...,Andrew Johnson.,hard,hard,S08_set3_a4
39,Abraham_Lincoln,Who was Lincoln's wife?,Mary Todd Lincoln,easy,easy,S08_set3_a4
40,Abraham_Lincoln,Who was Lincoln's wife?,Mary Todd.,easy,medium,S08_set3_a4
41,Abraham_Lincoln,Which political party did Lincoln represent wh...,Republican,medium,easy,S08_set3_a4
42,Abraham_Lincoln,Which political party did Lincoln represent wh...,Republican Party.,medium,medium,S08_set3_a4