In [1]:
import numpy as np 
import pandas as pd 
import re

In [2]:
comapines = pd.read_csv('scrape_data/raw_companies_data.csv')

In [3]:
comapines.head()

,company_name,company_url,rating,rating_count,industry,location,reviews,salaries,interviews,jobs,benefits,photos,highly_rated_for,critically_rated_for,page_number,scraped_at
0,Amazon Development Centre India,https://www.ambitionbox.com/overview/amazon-de...,3.8,(7.7k),Internet,Hyderabad +148 other locations,7.7k Reviews,39.5k Salaries,920 Interviews,21 Jobs,614 Benefits,13 Photos,"Company Culture, Work Life Balance",NaN,5,2026-09-15
1,Hindustan Unilever,https://www.ambitionbox.com/overview/hindustan...,4.1,(7.6k),FMCG,Mumbai +564 other locations,7.6k Reviews,21k Salaries,493 Interviews,25 Jobs,722 Benefits,6 Photos,"Skill Development, Company Culture, Work Life ...",NaN,5,2026-09-15
2,Megha Engineering & Infrastructures,https://www.ambitionbox.com/overview/megha-eng...,3.9,(7.5k),Engineering & Construction,Hyderabad +427 other locations,7.5k Reviews,19.7k Salaries,619 Interviews,27 Jobs,579 Benefits,48 Photos,"Work Life Balance, Job Security",NaN,5,2026-09-15
3,L&T Construction,https://www.ambitionbox.com/overview/l-and-t-c...,4.0,(7.5k),Engineering & Construction,Chennai +444 other locations,7.5k Reviews,19.4k Salaries,967 Interviews,-- Jobs,931 Benefits,42 Photos,"Job Security, Skill Development, Salary",NaN,5,2026-09-15
4,Tata Projects,https://www.ambitionbox.com/overview/tata-proj...,4.2,(7.3k),Engineering & Construction,Mumbai +297 other locations,7.3k Reviews,22.9k Salaries,660 Interviews,63 Jobs,606 Benefits,64 Photos,"Salary, Company Culture, Work Life Balance",NaN,5,2026-09-15

In [4]:
comapines['rating_count']

0       (7.7k)
1       (7.6k)
2       (7.5k)
3       (7.5k)
4       (7.3k)
         ...
9995     (168)
9996     (167)
9997     (167)
9998     (168)
9999     (167)
Name: rating_count, Length: 10000, dtype: object

In [5]:
def parse_count(val):
    if pd.isna(val):
        return None

    # Remove parentheses, spaces, and commas
    clean_val = re.sub(r"[\(\)\s,]", "", str(val)).lower()

    if "k" in clean_val:
        return float(clean_val.replace("k", "")) * 1_000
    elif "l" in clean_val:
        return float(clean_val.replace("l", "")) * 100_000
    elif "m" in clean_val:
        return float(clean_val.replace("m", "")) * 1_000_000
    else:
        try:
            return float(clean_val)
        except ValueError:
            return None

In [6]:
comapines['rating_count'] = comapines['rating_count'].apply(parse_count)

In [7]:
comapines ['headquarter'] = comapines['location'].str.split(' ').str[0].str.strip()

In [8]:
comapines['other_locations_count'] = comapines['location'].str.split(' ').str[1].str.replace('+', '').str.strip()

In [9]:
comapines['reviews'] = comapines['reviews'].str.split(' ').str[0].apply(parse_count)

In [15]:
comapines['salaries'] = comapines['salaries'].str.split(' ').str[0].apply(parse_count)

In [27]:
comapines['interviews'] = comapines['interviews'].str.split(' ').str[0]

In [32]:
comapines['jobs'] = comapines['jobs'].str.split().str[0]

In [36]:
comapines['benefits'] = comapines['benefits'].str.split(' ').str[0]

In [40]:
comapines['photos'] = comapines['photos'].str.split(' ').str[0]

In [45]:
clean_df = comapines[['company_name', 'company_url', 'industry', 'rating', 'reviews', 'headquarter', 'other_locations_count', 'highly_rated_for', 'critically_rated_for', 'salaries', 'interviews', 'jobs', 'benefits', 'photos']]
clean_df

,company_name,company_url,industry,rating,reviews,headquarter,other_locations_count,highly_rated_for,critically_rated_for,salaries,interviews,jobs,benefits,photos
0,Amazon Development Centre India,https://www.ambitionbox.com/overview/amazon-de...,Internet,3.8,7700.0,Hyderabad,148,"Company Culture, Work Life Balance",NaN,39500.0,920,21,614,13
1,Hindustan Unilever,https://www.ambitionbox.com/overview/hindustan...,FMCG,4.1,7600.0,Mumbai,564,"Skill Development, Company Culture, Work Life ...",NaN,21000.0,493,25,722,6
2,Megha Engineering & Infrastructures,https://www.ambitionbox.com/overview/megha-eng...,Engineering & Construction,3.9,7500.0,Hyderabad,427,"Work Life Balance, Job Security",NaN,19700.0,619,27,579,48
3,L&T Construction,https://www.ambitionbox.com/overview/l-and-t-c...,Engineering & Construction,4.0,7500.0,Chennai,444,"Job Security, Skill Development, Salary",NaN,19400.0,967,--,931,42
4,Tata Projects,https://www.ambitionbox.com/overview/tata-proj...,Engineering & Construction,4.2,7300.0,Mumbai,297,"Salary, Company Culture, Work Life Balance",NaN,22900.0,660,63,606,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Milliman,https://www.ambitionbox.com/overview/milliman-...,Management Consulting,3.1,168.0,Gurugram,5,NaN,"Promotions, Work Satisfaction, Skill Development",1100.0,25,5,18,--
9996,RxLogix Corporation,https://www.ambitionbox.com/overview/rxlogix-c...,Software Product,2.1,167.0,Noida,5,NaN,"Work Life Balance, Company Culture, Work Satis...",1200.0,23,22,12,--
9997,Qapitol Qa,https://www.ambitionbox.com/overview/qapitol-q...,IT Services & Consulting,3.8,167.0,Bengaluru,9,Work Life Balance,NaN,1300.0,20,70,16,--
9998,Lotus Footwear Enterprises,https://www.ambitionbox.com/overview/lotus-foo...,Fashion & Textile,4.0,168.0,Chennai,10,"Work Life Balance, Job Security, Salary",NaN,573.0,9,--,10,--
9999,3Pillar Global,https://www.ambitionbox.com/overview/3pillar-g...,Software Product,3.2,167.0,Noida,5,NaN,"Job Security, Promotions, Company Culture",1000.0,23,1,15,4

In [46]:
clean_df.to_csv('compaines_clean_data.csv', index=False)